### ISSUE TITLE
Mutually recursive type definitions

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/ppx_python#5]
It looks like `ppx_python` does not deal properly with mutually recursive type definitions. For example:

```ocaml
open Base
open Python_lib

type t = T of u list [@@deriving python]
and  u = U of t list [@@deriving python]
```

yields error:

```
Only variables are allowed as left-hand side of `let rec'
```

whereas `deriving.sexp` has no problem here for example.

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, which version of `ppx_python` are you using?
I would expect your example to work out of the box with the current github tip but note that the support for mutually recursive types has only been added in v0.15-preview. You can see an example using these as part of our testing suite in this [file](https://github.com/janestreet/ppx_python/blob/d30dc29406f35ffc89689ca7f379cbb249afd1fb/test/ppx_test.ml#L379-L405).

**Comment by jonathan-laurent** [comment]
I am using pythonlib and ppx_python v0.14.0 indeed.
Any idea when v0.15.0 will be officially released?

**Comment by LaurentMazare** [comment]
Sorry I don't have a good answer on when this is scheduled for, maybe @jeremiedimino would know better where this stands.

**Comment by ghost** [comment]
We are overdue a stable release and the next one is still a few months away. For now the best estimate I can give is "before the end of the year". This is because of a few factors, such as some internal restructuring of our core libraries that will take time to open source and some other internal priorities. I expect that we will be able to prioritise more the next stable release around September, and that it will reach the main opam repository before th end of the year.

**Comment by LaurentMazare** [comment]
v0.15 has been released last month, so closing this but feel free to re-open if you run into any issue.
